routes/web.php
<?php
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\SMSController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function ()
{
    return view('auth.login');
});
Route::get('privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('email-verified', 'HomeController@emailverified')->name('email-verified');
Route::get('/upload-data', 'Client\ClientController@uploadData')->name('upload-data');
Route::get('/upload-assigned', 'Client\ClientController@uploadDataForAssignedSchoolMDT')->name('upload-to-assigned-mdt');
Route::get('/black-list', 'Client\ClientController@blackList')->name('black-list');
Route::get('/clear',
	function(){

		Artisan::call('config:clear');
		Artisan::call('cache:clear');
		Artisan::call('config:cache');
	}
);

Auth::routes();



Route::group([
    'middleware'    => ['auth'],
    'prefix'        => 'client',
    'namespace'     => 'Client'
], function ()
{
    Route::get('/dashboard', 'ClientController@index')->name('client.dashboard');
	Route::get('/profile', 'ClientController@edit')->name('client-profile');
	Route::post('/admin-update', 'ClientController@update')->name('client-update');


	//User Routes
	Route::resource('clients','ClientController');
	Route::post('get-clients', 'ClientController@getClients')->name('admin.getClients');
	Route::post('get-client', 'ClientController@clientDetail')->name('admin.getClient');
	Route::get('client/delete/{id}', 'ClientController@destroy');
	Route::get('client-students/{id}', 'ClientController@students')->name("client-students");
	Route::get('student-quizzes/{id}', 'ClientController@quizzes')->name("student-quizzes");
	Route::get('quiz-answers/{id}', 'ClientController@answers')->name("quiz-answers");
	Route::post('delete-selected-clients', 'ClientController@deleteSelectedClients')->name('admin.delete-selected-clients');
	
	//User Routes
	Route::resource('questions','QuestionController');
	Route::post('get-questions', 'QuestionController@getClients')->name('admin.getQuestions');
	Route::post('get-question', 'QuestionController@clientDetail')->name('admin.getQuestion');
	Route::get('question/delete/{id}', 'QuestionController@destroy');
	Route::post('delete-selected-questions', 'QuestionController@deleteSelectedClients')->name('admin.delete-selected-questions');

	//schools Routes
	Route::resource('schools','SchoolController');
	Route::post('get-schools', 'SchoolController@getClients')->name('admin.getSchools');
	Route::post('get-school', 'SchoolController@clientDetail')->name('admin.getSchool');
	Route::get('school/delete/{id}', 'SchoolController@destroy');
	Route::post('delete-selected-schools', 'SchoolController@deleteSelectedClients')->name('admin.delete-selected-schools');

	//Buses Routes
	Route::resource('buses','BussController');
	Route::post('get-buses', 'BussController@getClients')->name('admin.getBuses');
	Route::post('get-buss', 'BussController@clientDetail')->name('admin.getBuss');
	Route::get('buss/delete/{id}', 'BussController@destroy');
	Route::post('delete-selected-buses', 'BussController@deleteSelectedClients')->name('admin.delete-selected-buses');

	//Mdt Routes
	Route::resource('mdt','MdtController');
	Route::post('get-mdts', 'MdtController@getClients')->name('client.getMdts');
	Route::post('get-mdt', 'MdtController@clientDetail')->name('client.getMdt');
	Route::get('mdt/delete/{id}', 'MdtController@destroy');
	Route::post('delete-selected-mdts', 'MdtController@deleteSelectedClients')->name('client.delete-selected-mdts');


	//Notification Route
	Route::resource('notification', 'NotificationController');

		//Attendance Route

		Route::resource('attendances', 'AttendanceController');

		//User Route
		Route::resource('users', UserController::class);
	
		//Message Route
		Route::resource('messages', 'MessageController');
	
		//Information Route
	
		Route::resource('informations', 'InformationController');
	
		//Grades Route
	
		Route::resource('grade', 'GradesController');
	
		//Schedules Route
	
		Route::resource('shedule', 'ShedulesController');
	
		//Announcements Route
	
		Route::resource('announcement', 'AnnouncementsController');
	
		//Library Route
	
		Route::resource('librarys', 'LibraryController');

<<<<<<< HEAD
		Route::resource('behavior', 'BehaviorController');

        //Accounting Route

        Route::resource('accounting', 'AccountingController');

        //Teacher Files Route

        Route::resource('teacher_files', 'TeacherfilesController');

        //Class Room Route

        Route::resource('class_room', 'ClassroomController');

        //School Bus Route

        Route::resource('school_bus', 'SchoolbusController');

        //Teacher Files Route

        Route::resource('system_settings', 'SystemsettingsController');

        //Teacher Files Route

        Route::resource('academic_settings', 'AcademicsettingsController');

		//Video Preview 

		Route::resource('video_preview', 'VideoPreviewController');

=======
>>>>>>> b97f45bfb816473ce02dc35b9aadd039b70fe1d2




});


Route::group([
    'middleware'    => ['auth', 'is_parent'],
    'prefix'        => 'parent',
    'namespace'     => 'Parent'
], function ()
{
    Route::get('/dashboard', 'ParentsController@index')->name('parent.dashboard');
	Route::get('/profile', 'ParentsController@edit')->name('parent-profile');
	Route::post('/admin-update', 'ParentsController@update')->name('parent-update');

		Route::resource('Notifications', 'NotificationController');

		//Message Route
		Route::resource('Message', 'MessageController');

		//Information Route

		Route::resource('Information', 'InformationController');

		//Grades Route

		Route::resource('Grades', 'GradesController');

		//Schedules Route

		Route::resource('Shedules', 'ShedulesController');

		//Announcements Route

		Route::resource('Announcements', 'AnnouncementsController');

		//Library Route

		Route::resource('Library', 'LibraryController');


});

Route::group([
    'middleware'    => ['auth','is_admin'],
    'prefix'        => 'admin',
    'namespace'     => 'Admin'
], function ()
{
    Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('/profile', 'AdminController@edit')->name('admin-profile');
    Route::post('/admin-update', 'AdminController@update')->name('admin-update');
    //Setting Routes
    Route::resource('setting','SettingController');

	//User Routes
	Route::resource('clients','ClientController');
	Route::post('get-clients', 'ClientController@getClients')->name('admin.getClients');
	Route::post('get-client', 'ClientController@clientDetail')->name('admin.getClient');
	Route::get('client/delete/{id}', 'ClientController@destroy');
	Route::get('client-students/{id}', 'ClientController@students')->name("client-students");
	Route::get('student-quizzes/{id}', 'ClientController@quizzes')->name("student-quizzes");
	Route::get('quiz-answers/{id}', 'ClientController@answers')->name("quiz-answers");
	Route::post('delete-selected-clients', 'ClientController@deleteSelectedClients')->name('admin.delete-selected-clients');

	//User Routes
	Route::resource('questions','QuestionController');
	Route::post('get-questions', 'QuestionController@getClients')->name('admin.getQuestions');
	Route::post('get-question', 'QuestionController@clientDetail')->name('admin.getQuestion');
	Route::get('question/delete/{id}', 'QuestionController@destroy');
	Route::post('delete-selected-questions', 'QuestionController@deleteSelectedClients')->name('admin.delete-selected-questions');

	//schools Routes
	Route::resource('schools','SchoolController');
	Route::post('get-schools', 'SchoolController@getClients')->name('admin.getSchools');
	Route::post('get-school', 'SchoolController@clientDetail')->name('admin.getSchool');
	Route::get('school/delete/{id}', 'SchoolController@destroy');
	Route::post('delete-selected-schools', 'SchoolController@deleteSelectedClients')->name('admin.delete-selected-schools');

	//Buses Routes
	Route::resource('buses','BussController');
	Route::post('get-buses', 'BussController@getClients')->name('admin.getBuses');
	Route::post('get-buss', 'BussController@clientDetail')->name('admin.getBuss');
	Route::get('buss/delete/{id}', 'BussController@destroy');
	Route::post('delete-selected-buses', 'BussController@deleteSelectedClients')->name('admin.delete-selected-buses');

	//Mdt Routes
	Route::resource('mdts','MdtController');
	Route::post('get-mdts', 'MdtController@getClients')->name('admin.getMdts');
	Route::post('get-mdt', 'MdtController@clientDetail')->name('admin.getMdt');
	Route::get('mdt/delete/{id}', 'MdtController@destroy');
	Route::post('delete-selected-mdts', 'MdtController@deleteSelectedClients')->name('admin.delete-selected-mdts');


	//Notification Route
	Route::resource('notifications', 'NotificationController');

		//Attendance Route

		Route::resource('attendance', 'AttendanceController');

		//User Route
		Route::resource('user', UserController::class);

		//Message Route
		Route::resource('message', 'MessageController');

		//Information Route

		Route::resource('information', 'InformationController');

		//Grades Route

		Route::resource('grades', 'GradesController');

		//Schedules Route

		Route::resource('shedules', 'ShedulesController');

		//Announcements Route

		Route::resource('announcements', 'AnnouncementsController');

		//Library Route

        Route::resource('library', 'LibraryController');

        //Behavior Route

        Route::resource('behavior', 'BehaviorController');

        //Accounting Route

        Route::resource('accounting', 'AccountingController');

        //Teacher Files Route

app/Http/Controllers/Client/AccountingController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountingController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Video preview';
	    return view('admin.accounting.index',compact('title'));
    }
    //

}

app/Http/Controllers/Client/AnnouncementsController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AnnouncementsController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Announcements';
	    return view('client.announcements.index',compact('title'));
    }
    //

}

app/Http/Controllers/Client/AttendanceController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Attendance';
	    return view('client.attendance.index',compact('title'));
    }
}

app/Http/Controllers/Client/ClassroomController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassroomController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Classroom';
	    return view('admin.classroom.index',compact('title'));
    }
    //

}

app/Http/Controllers/Client/GradesController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GradesController extends Controller
{
     /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index()
   {
       $title = 'Grades';
       return view('client.grades.index',compact('title'));
   }

}

app/Http/Controllers/Client/InformationController.php
<?php


namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class InformationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Information';
	    return view('client.information.index',compact('title'));
    }
}

app/Http/Controllers/Client/LibraryController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LibraryController extends Controller
{
         /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Library';
	    return view('client.library.index',compact('title'));
    }
    //
}

app/Http/Controllers/Client/MessageController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'User';
	    return view('client.message.index',compact('title'));
    }
}

app/Http/Controllers/Client/NotificationController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class NotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Notifications';
	    return view('client.notifications.index',compact('title'));
    }
}

app/Http/Controllers/Client/ShedulesController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ShedulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Shedules';
	    return view('admin.shedules.index',compact('title'));
    }
    //
}

app/Http/Controllers/Client/TeacherfilesController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TeacherfilesController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $title = 'Behavior';
	    return view('admin.teacherfiles.index',compact('title'));
    }
    //

}

resources/views/admin/clients/create.blade.php
@extends('admin.layouts.master')
@section('title',$title)
@section('content')
  <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader" kt-hidden-height="54" style="">
      <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
          <!--begin::Page Heading-->
          <div class="d-flex align-items-baseline flex-wrap mr-5">
            <!--begin::Page Title-->
            <h5 class="text-dark font-weight-bold my-1 mr-5">Dashboard</h5>
            <!--end::Page Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
              <li class="breadcrumb-item text-muted">
                <a href="" class="text-muted">Manage Clients</a>
              </li>
              <li class="breadcrumb-item text-muted">
                <a href="" class="text-muted">Add Client</a>
              </li>
            </ul>
            <!--end::Breadcrumb-->
          </div>
          <!--end::Page Heading-->
        </div>
        <!--end::Info-->
      </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
      <!--begin::Container-->
      <div class="container">
        <!--begin::Card-->
        <div class="card card-custom card-sticky" id="kt_page_sticky_card">
          <div class="card-header" style="">
            <div class="card-title">
              <h3 class="card-label">Client Add Form
                <i class="mr-2"></i>
                <small class="">try to scroll the page</small></h3>

            </div>
            <div class="card-toolbar">

              <a href="{{ route('clients.index') }}" class="btn btn-light-primary
              font-weight-bolder mr-2">
                <i class="ki ki-long-arrow-back icon-sm"></i>Back</a>

              <div class="btn-group">
                <a href="{{ route('clients.store') }}"  onclick="event.preventDefault(); document.getElementById('client_add_form').submit();" id="kt_btn" class="btn btn-primary font-weight-bolder">
                  <i class="ki ki-check icon-sm"></i>Save</a>



              </div>
            </div>
          </div>
          <div class="card-body">
          @include('admin.partials._messages')
          <!--begin::Form-->
            {{ Form::open([ 'route' => 'clients.store','class'=>'form' ,"id"=>"client_add_form", 'enctype'=>'multipart/form-data']) }}
              @csrf
              <div class="row">
                <div class="col-xl-2"></div>
                <div class="col-xl-8">
                  <div class="my-5">
                    <div class="form-group row {{ $errors->has('name') ? 'has-error' : '' }}">
                      <label class="col-3">Name</label>
                      <div class="col-9">
                        {{ Form::text('name', null, ['class' => 'form-control form-control-solid','id'=>'name','placeholder'=>'Enter Name','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('email') ? 'has-error' : '' }}">
                      <label class="col-3">Email</label>
                      <div class="col-9">
                        {{ Form::email('email', null, ['class' => 'form-control form-control-solid','id'=>'email','placeholder'=>'Enter Here','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('email') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('first_name') ? 'has-error' : '' }}">
                      <label class="col-3">First Name</label>
                      <div class="col-9">
                        {{ Form::email('first_name', null, ['class' => 'form-control form-control-solid','id'=>'email','placeholder'=>'Enter Here','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('first_name') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('last_name') ? 'has-error' : '' }}">
                      <label class="col-3">Last Name</label>
                      <div class="col-9">
                        {{ Form::email('last_name', null, ['class' => 'form-control form-control-solid','id'=>'email','placeholder'=>'Enter Here','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('last_name') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('phone') ? 'has-error' : '' }}">
                      <label class="col-3">Phone</label>
                      <div class="col-9">
                        {{ Form::email('phone', null, ['class' => 'form-control form-control-solid','id'=>'email','placeholder'=>'Enter Here','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('phone') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('password') ? 'has-error' : '' }}">
                      <label class="col-3">Password</label>
                      <div class="col-9">
                        {{ Form::text('password', null, ['class' => 'form-control form-control-solid','id'=>'password','required'=>'true']) }}
                        <span class="text-danger">{{ $errors->first('password') }}</span>
                      </div>
                    </div>
                    <div class="form-group row {{ $errors->has('image') ? 'has-error' : '' }}">
                      <label class="col-3">Image</label>
                      <div class="col-9">
                        <input type="file" class="custom-file-input" name="image" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>

                        <span class="text-danger">{{ $errors->first('image') }}</span>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-3 col-form-label">Gender</label>
                      <div class="col-3">
                          <div class="radio-inline">
                              <label class="radio">
                                  <input type="radio" checked value="1" name="gender">
                                  <span></span>Male</label>
                              <label class="radio">
                                  <input type="radio" value="0" name="gender">
                                  <span></span>Female</label>

                          </div>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-3 col-form-label">Active</label>
                      <div class="col-3">
                         <span class="switch switch-outline switch-icon switch-success">
                          <label><input type="checkbox" checked="checked" name="active" value="1">
                            <span></span>
                          </label>
                        </span>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-3 col-form-label">Employee</label>
                      <div class="col-3">
                         <span class="switch switch-outline switch-icon switch-success">
                          <label><input type="checkbox" checked="checked" name="is_employee" value="1">
                            <span></span>
                          </label>
                        </span>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-3 col-form-label">Parent</label>
                      <div class="col-3">
                         <span class="switch switch-outline switch-icon switch-success">
                          <label><input type="checkbox" checked="checked" name="is_parent" value="1">
                            <span></span>
                          </label>
                        </span>
                      </div>
                    </div>

                  </div>

                </div>
                <div class="col-xl-2"></div>
              </div>
          {{Form::close()}}
            <!--end::Form-->
          </div>
        </div>
        <!--end::Card-->

      </div>
      <!--end::Container-->
    </div>
    <!--end::Entry-->
  </div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.master')
@section('title',$title)
@section('content')
  <!--begin::Card-->
  <div class="card card-custom ">
    <div class="card-header">
      <div class="card-title">
            <span class="card-icon">
                <i class="flaticon-users text-primary"></i>
            </span>
        <h3 class="card-label">Client List</h3>
	      <div class="d-flex align-items-center ">
		      <a class="btn btn-danger font-weight-bolder" onclick="del_selected()" href="javascript:void(0)"> <i class="la la-trash-o"></i>Delete All</a>
	      </div>
      </div>
      <div class="card-toolbar">

        <!--begin::Button-->
        <a href="{{ route('clients.create') }}" class="btn btn-primary font-weight-bolder">
											<span class="svg-icon svg-icon-md">
												<!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
												<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
													<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
														<rect x="0" y="0" width="24" height="24" />
														<circle fill="#000000" cx="9" cy="15" r="6" />
														<path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
													</g>
												</svg>
                        <!--end::Svg Icon-->
											</span>New Record</a>
        <!--end::Button-->
      </div>
    </div>
    <div class="card-body">
	    @include('admin.partials._messages')
      <div class="">
	      <form action="{{route('admin.delete-selected-clients')}}" method="post" id="client_form">
	      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <!--begin: Datatable-->
      <table class="table table-bordered table-hover table-checkable" id="clients" style="margin-top: 13px !important">
        <thead>
        <tr>
	        <th>
		        <label class="checkbox checkbox-outline checkbox-success"><input type="checkbox"><span></span></label>

	        </th>

          <th>Name</th>
          <th>Email</th>
          <th>Status</th>
          <th>Created At</th>
          <th>Actions</th>
        </tr>
        </thead>
      </table>
	      </form>
      <!--end: Datatable-->
    </div>
    </div>
	  <!-- Modal-->
	  <div class="modal fade" id="clientModel" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
			  <div class="modal-content">
				  <div class="modal-header">
					  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					  <h4 class="modal-title" id="myModalLabel">Client Detail</h4> </div>
				  <div class="modal-body"></div>
				  <div class="modal-footer">
					  <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
				  </div>
			  </div>
		  </div>
	  </div>
  </div>
  <!--end::Card-->
@endsection
@section('stylesheets')
  <!--begin::Page Vendors Styles(used by this page)-->
  <link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" rel="stylesheet"
        type="text/css" />
  <!--end::Page Vendors Styles-->
@endsection
@section('scripts')
  <!--begin::Page Vendors(used by this page)-->
  <script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
  <!--end::Page Vendors-->
  <script>

      $(document).on('click', 'th input:checkbox', function () {

          var that = this;
          $(this).closest('table').find('tr > td:first-child input:checkbox')
              .each(function () {
                  this.checked = that.checked;
                  $(this).closest('tr').toggleClass('selected');
              });
      });
      var clients = $('#clients').DataTable( {
          "order": [
              [1, 'asc']
          ],
          "processing": true,
          "serverSide": true,
          "searchDelay": 500,
          "responsive": true,
          "ajax": {
              "url":"{{ route('admin.getClients') }}",
              "dataType":"json",
              "type":"POST",
              "data":{"_token":"<?php echo csrf_token() ?>"}
          },
          "columns":[
              {"data":"id","searchable":false,"orderable":false},
              {"data":"name"},
              {"data":"email"},
              {"data":"active"},
              {"data":"created_at"},
              {"data":"action","searchable":false,"orderable":false}
          ]
      } );
      function viewInfo(id) {

          var CSRF_TOKEN = '{{ csrf_token() }}';
          $.post("{{ route('admin.getClient') }}", {_token: CSRF_TOKEN, id: id}).done(function (response) {
              $('.modal-body').html(response);
              $('#clientModel').modal('show');

          });
      }
      function del(id){
          Swal.fire({
              title: "Are you sure?",
              text: "You won't be able to revert this!",
          icon: "warning",
              showCancelButton: true,
              confirmButtonText: "Yes, delete it!"
      }).then(function(result) {
              if (result.value) {
                  Swal.fire(
                      "Deleted!",
                      "Your client has been deleted.",
                      "success"
                  );
                  var APP_URL = {!! json_encode(url('/')) !!}
                  window.location.href = APP_URL+"/admin/client/delete/"+id;
              }
          });
      }
      function del_selected(){
          Swal.fire({
              title: "Are you sure?",
              text: "You won't be able to revert this!",
              icon: "warning",
              showCancelButton: true,
              confirmButtonText: "Yes, delete it!"
          }).then(function(result) {
              if (result.value) {
                  Swal.fire(
                      "Deleted!",
                      "Your clients has been deleted.",
                      "success"
                  );
                  $("#client_form").submit();
              }
          });
      }

  </script>
@endsection